# Project Specific Makefile
# =========================

# NOTE: Whitespace chars at end of line can result in invalid entries


# Project Variables
# =================

# run 'make boards' for options
# diecimila - Diecimila Board with ATMEGA 168
BOARD := atmega328
#BOARD := pro5v

# Adjust library path as required (space separated)
LIBRARYPATH := /usr/share/arduino/libraries ~/Git/RFM69W/libraries

# Include Arduino Makefile
# ========================
include ~/bin/arduino.mk
# Arduino Makefile downloaded from:
# http://ed.am/dev/make/arduino-mk



